version: "3.3"
services:
  maverick:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: maverick:dev
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: make docker-run
  nginx:
    build:
      context: ./_dev/.tools
      dockerfile: ./nginx/Dockerfile-nginx
      args:
        build_domain: jsorge.local
    environment:
      CA_SSL: "false" # change to "true" for production
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Public:/home/maverick/Public
      - ./.tools/nginx/ssl:/var/www/ssl
      - ./.tools/nginx/logs:/var/log/nginx
    depends_on:
      - maverick
  
