version: "3.3"
services:
  maverick:
    build:
      context: .
      dockerfile: Dockerfile
    image: maverick:dev
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./Public:/home/maverick/Public
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - maverick
